"""
SpaceSort - Database wrapper using team-db CLI for shared SQLite via Turso.
All database access must go through this module for consistency.
"""

import subprocess
import json
from typing import Any, Optional


def execute(sql: str) -> list[dict[str, Any]]:
    """Execute a SQL statement via team-db CLI and return results as list of dicts."""
    result = subprocess.run(
        ["team-db", sql],
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(f"team-db error: {result.stderr.strip()}")
    if not result.stdout.strip():
        return []
    return json.loads(result.stdout)


def query(sql: str) -> list[dict[str, Any]]:
    """Read-only query convenience wrapper."""
    return execute(sql)


def mutate(sql: str) -> list[dict[str, Any]]:
    """Write operation convenience wrapper."""
    return execute(sql)


# ── Schema initialization (idempotent) ──────────────────────────────

SCHEMA_SQL = """
-- Users table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    stripe_customer_id TEXT,
    subscription_status TEXT DEFAULT 'none'
);

-- Spaces (rooms/closets/etc) uploaded by users
CREATE TABLE IF NOT EXISTS spaces (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT,
    photo_path TEXT,
    dimensions TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Organization plans generated by AI
CREATE TABLE IF NOT EXISTS plans (
    id TEXT PRIMARY KEY,
    space_id TEXT NOT NULL REFERENCES spaces(id),
    user_id TEXT NOT NULL REFERENCES users(id),
    plan_data TEXT NOT NULL,
    shopping_list TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Shopping list items
CREATE TABLE IF NOT EXISTS shopping_items (
    id TEXT PRIMARY KEY,
    plan_id TEXT NOT NULL REFERENCES plans(id),
    product_name TEXT NOT NULL,
    product_url TEXT,
    retailer TEXT,
    price REAL,
    currency TEXT DEFAULT 'USD',
    affiliate_url TEXT,
    category TEXT,
    quantity INTEGER DEFAULT 1
);

-- Payments / orders
CREATE TABLE IF NOT EXISTS payments (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    stripe_session_id TEXT UNIQUE,
    amount REAL NOT NULL,
    currency TEXT DEFAULT 'USD',
    status TEXT NOT NULL DEFAULT 'pending',
    type TEXT NOT NULL DEFAULT 'one_time',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- KPI tracking
CREATE TABLE IF NOT EXISTS kpi_events (
    id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    user_id TEXT REFERENCES users(id),
    metadata TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
"""


def init_db() -> None:
    """Initialize all tables. Safe to call multiple times."""
    for statement in SCHEMA_SQL.split(';'):
        stmt = statement.strip()
        if stmt:
            try:
                execute(stmt + ';')
            except RuntimeError as e:
                # Table may already exist - ignore if so
                if "already exists" not in str(e):
                    raise